figure;  hold on;

plot3(  allPtsReshaped(1, :), ...
        allPtsReshaped(2, :), ...
        allPtsReshaped(3, :), ...
        '.');

plot3(ptCenter(1), ptCenter(2), ptCenter(3), '.r');

plot3(  cellsRegions.RegionDesc(cellID).Pixels(1, :), ...
        cellsRegions.RegionDesc(cellID).Pixels(2, :), ...
        cellsRegions.RegionDesc(cellID).Pixels(3, :), ...
        '.r');
    
plot3(  cellsRegions.Pixels(1, :), ...
        cellsRegions.Pixels(2, :), ...
        cellsRegions.Pixels(3, :), ...
        '.r');
    


hold off;